### ISSUE TITLE
Update apiVersion for Deployment

### ISSUE THREAD

**Issue by tlnd** [openvnf/sftp-server#7]
Starting with Kubernetes v1.16 `Deployment`, `StatefulSet`, and `DaemonSet`  are no longer available in API version `extensions/v1beta1`, as they are available in `apps/v1` since v1.9: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The templates need to be updated to consider this and support k8s 1.16.

**Comment by mgumz** [comment]
The deployment looks valid to me already:

https://github.com/openvnf/sftp-server/blob/master/templates/deployment.yaml#L1-L2

**Comment by tlnd** [comment]
True
